# Generated by Django 3.1.5 on 2021-02-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbtestapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Student_dbtest',
        ),
    ]
