# Generated by Django 3.1.5 on 2021-03-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('relation', models.CharField(max_length=10)),
                ('relativeName', models.CharField(max_length=50)),
                ('relativeSurname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('mobile', models.IntegerField(max_length=12, null=True)),
                ('declarationPlace', models.CharField(max_length=50)),
                ('declarationDate', models.DateField()),
            ],
        ),
    ]
