# Generated by Django 3.1.5 on 2021-03-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdata',
            name='mobile',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
