# Generated by Django 3.1.5 on 2021-03-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20210313_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdata',
            name='aadharCard',
            field=models.FileField(null=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='applicationdata',
            name='declaration',
            field=models.FileField(null=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='applicationdata',
            name='photo',
            field=models.FileField(null=True, upload_to='documents'),
        ),
    ]
