# Generated by Django 3.1.5 on 2021-03-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20210319_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdata',
            name='aadharCard',
            field=models.ImageField(null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='applicationdata',
            name='declaration',
            field=models.ImageField(null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='applicationdata',
            name='photo',
            field=models.ImageField(null=True, upload_to='documents'),
        ),
    ]
