# Generated by Django 3.1.5 on 2021-03-21 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20210320_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdata',
            name='application_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
