# Generated by Django 3.1.5 on 2021-03-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_applicationdata_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdata',
            name='appointed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationdata',
            name='generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationdata',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationdata',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
